TRANSLATIONS = {
    "Русский": {
        "language": "Язык", "edit_save": "Редактировать сохранение", "view_backups": "Просмотр бэкапов", "github": "GitHub",
        "choose_file": "Открыть сохранение", "invalid": "Ошибка", "saved": "Сохранение успешно изменено.",
        "backup_created": "Создан бэкап старого сохранения:\n{path}", "mods_title": "Обнаружены моды",
        "mods_warning": "SaveSDV обнаружила моды в вашем сохранении. Пожалуйста, учтите, что моды не поддерживаются SaveSDV полностью и могут повредить или испортить ваше сохранение. Пожалуйста, всегда создавайте резервные копии при использовании SaveSDV.",
        "player_name": "Имя персонажа", "farm_name": "Название фермы", "money": "Деньги", "save_changes": "Сохранить изменения", "cancel": "Назад",
        "backups_title": "Доступные бэкапы", "restore": "Распаковать бэкап", "no_backups": "Бэкапов пока нет.",
        "restore_done": "Бэкап распакован в:\n{path}",
        "backup_confirm": "Перед изменением SaveSDV автоматически создаёт бэкап всего каталога сохранения.",
        "footer": "Создано FedotovDev и участниками SaveSDV. Не связано со Stardew Valley и ConcernedApe. Не является официальным продуктом Stardew Valley.",
        "main_title": "Редактор сохранений Stardew Valley, версия 1.0", "editing_title": "SaveSDV - Редактирование сохранения ({name})", "backups_window": "SaveSDV - Бэкапы",
    },
    "English": {
        "language": "Language", "edit_save": "Edit Save", "view_backups": "View Backups", "github": "GitHub", "choose_file": "Open Save",
        "invalid": "Error", "saved": "Save edited successfully.", "backup_created": "A backup of the old save was created:\n{path}", "mods_title": "Mods detected",
        "mods_warning": "SaveSDV has detected mods in your save file. Please be aware that mods aren't fully supported by SaveSDV, and they may wreck or corrupt your save. Please always create backups when using SaveSDV.",
        "player_name": "Player name", "farm_name": "Farm name", "money": "Money", "save_changes": "Save Changes", "cancel": "Back",
        "backups_title": "Available Backups", "restore": "Extract Backup", "no_backups": "There are no backups yet.", "restore_done": "Backup extracted to:\n{path}",
        "backup_confirm": "Before any edit, SaveSDV automatically creates a backup of the entire save folder.",
        "footer": "Made by FedotovDev and SaveSDV contributors. Not affiliated with Stardew Valley and ConcernedApe in any way. Not an official Stardew Valley product.",
        "main_title": "SaveSDV v1.0 Stardew Valley Save Editor", "editing_title": "SaveSDV - Editing save ({name})", "backups_window": "SaveSDV - Backups",
    },
    "Deutsch": {
        "language": "Sprache", "edit_save": "Spielstand bearbeiten", "view_backups": "Backups anzeigen", "github": "GitHub", "choose_file": "Spielstand öffnen", "invalid": "Fehler",
        "saved": "Spielstand erfolgreich geändert.", "backup_created": "Ein Backup des alten Spielstands wurde erstellt:\n{path}", "mods_title": "Mods erkannt",
        "mods_warning": "SaveSDV hat Mods in Ihrem Spielstand erkannt. Bitte beachten Sie, dass Mods von SaveSDV nicht vollständig unterstützt werden und Ihren Spielstand beschädigen oder zerstören können. Erstellen Sie bei der Verwendung von SaveSDV immer Backups.",
        "player_name": "Spielername", "farm_name": "Hofname", "money": "Geld", "save_changes": "Änderungen speichern", "cancel": "Zurück", "backups_title": "Verfügbare Backups", "restore": "Backup extrahieren", "no_backups": "Noch keine Backups.", "restore_done": "Backup wurde extrahiert nach:\n{path}",
        "backup_confirm": "Vor jeder Änderung erstellt SaveSDV automatisch ein Backup des gesamten Spielstandsordners.", "footer": "Erstellt von FedotovDev und den SaveSDV-Mitwirkenden. In keiner Weise mit Stardew Valley oder ConcernedApe verbunden. Kein offizielles Stardew-Valley-Produkt.",
        "main_title": "SaveSDV v1.0 Stardew Valley Save Editor", "editing_title": "SaveSDV - Spielstand bearbeiten ({name})", "backups_window": "SaveSDV - Backups",
    },
    "Español": {
        "language": "Idioma", "edit_save": "Editar partida", "view_backups": "Ver copias de seguridad", "github": "GitHub", "choose_file": "Abrir partida", "invalid": "Error", "saved": "Partida editada correctamente.",
        "backup_created": "Se creó una copia de seguridad de la partida anterior:\n{path}", "mods_title": "Mods detectados", "mods_warning": "SaveSDV ha detectado mods en tu partida. Ten en cuenta que los mods no son compatibles al 100 % con SaveSDV y pueden dañar o corromper la partida. Crea siempre copias de seguridad al usar SaveSDV.",
        "player_name": "Nombre del jugador", "farm_name": "Nombre de la granja", "money": "Dinero", "save_changes": "Guardar cambios", "cancel": "Atrás", "backups_title": "Copias disponibles", "restore": "Extraer copia", "no_backups": "Todavía no hay copias.", "restore_done": "Copia extraída en:\n{path}", "backup_confirm": "Antes de cada edición, SaveSDV crea automáticamente una copia de toda la carpeta de la partida.",
        "footer": "Creado por FedotovDev y los colaboradores de SaveSDV. No está afiliado de ninguna forma con Stardew Valley ni ConcernedApe. No es un producto oficial de Stardew Valley.", "main_title": "SaveSDV v1.0 Stardew Valley Save Editor", "editing_title": "SaveSDV - Editando partida ({name})", "backups_window": "SaveSDV - Copias",
    },
    "Čeština": {
        "language": "Jazyk", "edit_save": "Upravit uloženou hru", "view_backups": "Zobrazit zálohy", "github": "GitHub", "choose_file": "Otevřít uloženou hru", "invalid": "Chyba", "saved": "Uložená hra byla úspěšně upravena.", "backup_created": "Byla vytvořena záloha původní uložené hry:\n{path}", "mods_title": "Byly nalezeny mody", "mods_warning": "SaveSDV zjistil mody ve vašem uloženém souboru. Mody nejsou SaveSDV plně podporovány a mohou uloženou hru poškodit nebo znehodnotit. Při používání SaveSDV vždy vytvářejte zálohy.", "player_name": "Jméno hráče", "farm_name": "Název farmy", "money": "Peníze", "save_changes": "Uložit změny", "cancel": "Zpět", "backups_title": "Dostupné zálohy", "restore": "Rozbalit zálohu", "no_backups": "Zatím nejsou žádné zálohy.", "restore_done": "Záloha byla rozbalena do:\n{path}", "backup_confirm": "Před každou úpravou SaveSDV automaticky vytvoří zálohu celé složky se hrou.", "footer": "Vytvořili FedotovDev a přispěvatelé SaveSDV. Není nijak spojen se Stardew Valley ani ConcernedApe. Nejedná se o oficiální produkt Stardew Valley.", "main_title": "SaveSDV v1.0 - editor uložených her Stardew Valley", "editing_title": "SaveSDV - Úprava uložené hry ({name})", "backups_window": "SaveSDV - Zálohy",
    },
    "Polski": {"language":"Język","edit_save":"Edytuj zapis","view_backups":"Wyświetl kopie zapasowe","github":"GitHub","choose_file":"Otwórz zapis","invalid":"Błąd","saved":"Zapis został pomyślnie zmieniony.","backup_created":"Utworzono kopię starego zapisu:\n{path}","mods_title":"Wykryto mody","mods_warning":"SaveSDV wykrył mody w pliku zapisu. Mody nie są w pełni obsługiwane przez SaveSDV i mogą uszkodzić zapis. Zawsze twórz kopie zapasowe podczas używania SaveSDV.","player_name":"Imię gracza","farm_name":"Nazwa farmy","money":"Pieniądze","save_changes":"Zapisz zmiany","cancel":"Wstecz","backups_title":"Dostępne kopie","restore":"Wypakuj kopię","no_backups":"Brak kopii zapasowych.","restore_done":"Kopia została wypakowana do:\n{path}","backup_confirm":"Przed każdą zmianą SaveSDV automatycznie tworzy kopię całego folderu zapisu.","footer":"Stworzone przez FedotovDev i współtwórców SaveSDV. Nie jest powiązane ze Stardew Valley ani ConcernedApe. Nie jest oficjalnym produktem Stardew Valley.","main_title":"SaveSDV v1.0 - edytor zapisów Stardew Valley","editing_title":"SaveSDV - Edycja zapisu ({name})","backups_window":"SaveSDV - Kopie"},
    "Українська": {"language":"Мова","edit_save":"Редагувати збереження","view_backups":"Переглянути резервні копії","github":"GitHub","choose_file":"Відкрити збереження","invalid":"Помилка","saved":"Збереження успішно змінено.","backup_created":"Створено резервну копію старого збереження:\n{path}","mods_title":"Виявлено моди","mods_warning":"SaveSDV виявила моди у вашому збереженні. Моди не підтримуються SaveSDV повністю та можуть пошкодити або зіпсувати збереження. Будь ласка, завжди створюйте резервні копії під час використання SaveSDV.","player_name":"Ім'я гравця","farm_name":"Назва ферми","money":"Гроші","save_changes":"Зберегти зміни","cancel":"Назад","backups_title":"Доступні резервні копії","restore":"Розпакувати копію","no_backups":"Резервних копій ще немає.","restore_done":"Копію розпаковано до:\n{path}","backup_confirm":"Перед кожною зміною SaveSDV автоматично створює резервну копію всієї папки збереження.","footer":"Створено FedotovDev та учасниками SaveSDV. Ніяк не пов'язано зі Stardew Valley та ConcernedApe. Не є офіційним продуктом Stardew Valley.","main_title":"SaveSDV v1.0 - редактор збережень Stardew Valley","editing_title":"SaveSDV - Редагування збереження ({name})","backups_window":"SaveSDV - Резервні копії"},
    "Italiano": {"language":"Lingua","edit_save":"Modifica salvataggio","view_backups":"Visualizza backup","github":"GitHub","choose_file":"Apri salvataggio","invalid":"Errore","saved":"Salvataggio modificato correttamente.","backup_created":"È stato creato un backup del vecchio salvataggio:\n{path}","mods_title":"Mod rilevati","mods_warning":"SaveSDV ha rilevato mod nel salvataggio. I mod non sono completamente supportati da SaveSDV e possono danneggiare o corrompere il salvataggio. Crea sempre dei backup quando usi SaveSDV.","player_name":"Nome del giocatore","farm_name":"Nome della fattoria","money":"Denaro","save_changes":"Salva modifiche","cancel":"Indietro","backups_title":"Backup disponibili","restore":"Estrai backup","no_backups":"Non ci sono ancora backup.","restore_done":"Backup estratto in:\n{path}","backup_confirm":"Prima di ogni modifica, SaveSDV crea automaticamente un backup dell'intera cartella del salvataggio.","footer":"Realizzato da FedotovDev e dai contributori di SaveSDV. Non affiliato in alcun modo a Stardew Valley e ConcernedApe. Non è un prodotto ufficiale di Stardew Valley.","main_title":"SaveSDV v1.0 - editor dei salvataggi Stardew Valley","editing_title":"SaveSDV - Modifica salvataggio ({name})","backups_window":"SaveSDV - Backup"},
    "Français": {"language":"Langue","edit_save":"Modifier la sauvegarde","view_backups":"Voir les sauvegardes","github":"GitHub","choose_file":"Ouvrir la sauvegarde","invalid":"Erreur","saved":"Sauvegarde modifiée avec succès.","backup_created":"Une copie de l'ancienne sauvegarde a été créée :\n{path}","mods_title":"Mods détectés","mods_warning":"SaveSDV a détecté des mods dans votre sauvegarde. Les mods ne sont pas entièrement pris en charge par SaveSDV et peuvent endommager ou corrompre votre sauvegarde. Créez toujours des sauvegardes lorsque vous utilisez SaveSDV.","player_name":"Nom du joueur","farm_name":"Nom de la ferme","money":"Argent","save_changes":"Enregistrer les modifications","cancel":"Retour","backups_title":"Sauvegardes disponibles","restore":"Extraire la sauvegarde","no_backups":"Aucune sauvegarde pour le moment.","restore_done":"Sauvegarde extraite vers :\n{path}","backup_confirm":"Avant toute modification, SaveSDV crée automatiquement une sauvegarde de tout le dossier de la partie.","footer":"Créé par FedotovDev et les contributeurs de SaveSDV. Sans affiliation avec Stardew Valley ou ConcernedApe. Ce n'est pas un produit officiel de Stardew Valley.","main_title":"SaveSDV v1.0 - éditeur de sauvegardes Stardew Valley","editing_title":"SaveSDV - Modification de la sauvegarde ({name})","backups_window":"SaveSDV - Sauvegardes"},
    "Türkçe": {"language":"Dil","edit_save":"Kayıdı Düzenle","view_backups":"Yedekleri Görüntüle","github":"GitHub","choose_file":"Kaydı aç","invalid":"Hata","saved":"Kayıt başarıyla düzenlendi.","backup_created":"Eski kaydın yedeği oluşturuldu:\n{path}","mods_title":"Modlar algılandı","mods_warning":"SaveSDV kayıt dosyanızda modlar algıladı. Modlar SaveSDV tarafından tamamen desteklenmez ve kaydınızı bozabilir. SaveSDV kullanırken lütfen her zaman yedek oluşturun.","player_name":"Oyuncu adı","farm_name":"Çiftlik adı","money":"Para","save_changes":"Değişiklikleri kaydet","cancel":"Geri","backups_title":"Mevcut yedekler","restore":"Yedeği çıkar","no_backups":"Henüz yedek yok.","restore_done":"Yedek şu konuma çıkarıldı:\n{path}","backup_confirm":"Her düzenlemeden önce SaveSDV tüm kayıt klasörünün otomatik yedeğini oluşturur.","footer":"FedotovDev ve SaveSDV katkıcıları tarafından yapılmıştır. Stardew Valley ve ConcernedApe ile hiçbir şekilde bağlantılı değildir. Resmî bir Stardew Valley ürünü değildir.","main_title":"SaveSDV v1.0 - Stardew Valley Kayıt Düzenleyici","editing_title":"SaveSDV - Kayıt düzenleniyor ({name})","backups_window":"SaveSDV - Yedekler"},
    "Română": {"language":"Limbă","edit_save":"Editează salvarea","view_backups":"Vezi copiile","github":"GitHub","choose_file":"Deschide salvarea","invalid":"Eroare","saved":"Salvarea a fost modificată cu succes.","backup_created":"A fost creată o copie de siguranță a salvării vechi:\n{path}","mods_title":"Moduri detectate","mods_warning":"SaveSDV a detectat moduri în fișierul de salvare. Modurile nu sunt suportate complet de SaveSDV și pot deteriora sau corupe salvarea. Creează întotdeauna copii de siguranță când folosești SaveSDV.","player_name":"Numele jucătorului","farm_name":"Numele fermei","money":"Bani","save_changes":"Salvează modificările","cancel":"Înapoi","backups_title":"Copii disponibile","restore":"Extrage copia","no_backups":"Nu există încă copii.","restore_done":"Copia a fost extrasă în:\n{path}","backup_confirm":"Înainte de fiecare modificare, SaveSDV creează automat o copie a întregului folder de salvare.","footer":"Creat de FedotovDev și contribuitorii SaveSDV. Nu este afiliat în niciun fel cu Stardew Valley și ConcernedApe. Nu este un produs oficial Stardew Valley.","main_title":"SaveSDV v1.0 - editor de salvări Stardew Valley","editing_title":"SaveSDV - Editare salvare ({name})","backups_window":"SaveSDV - Copii"},
    "Slovenčina": {"language":"Jazyk","edit_save":"Upraviť uloženú hru","view_backups":"Zobraziť zálohy","github":"GitHub","choose_file":"Otvoriť uloženú hru","invalid":"Chyba","saved":"Uložená hra bola úspešne upravená.","backup_created":"Bola vytvorená záloha pôvodnej uloženej hry:\n{path}","mods_title":"Boli zistené mody","mods_warning":"SaveSDV zistil mody vo vašom uloženom súbore. Mody nie sú v SaveSDV plne podporované a môžu poškodiť alebo znehodnotiť uloženú hru. Pri používaní SaveSDV vždy vytvárajte zálohy.","player_name":"Meno hráča","farm_name":"Názov farmy","money":"Peniaze","save_changes":"Uložiť zmeny","cancel":"Späť","backups_title":"Dostupné zálohy","restore":"Rozbaliť zálohu","no_backups":"Zatiaľ nie sú žiadne zálohy.","restore_done":"Záloha bola rozbalená do:\n{path}","backup_confirm":"Pred každou úpravou SaveSDV automaticky vytvorí zálohu celého priečinka uloženej hry.","footer":"Vytvorili FedotovDev a prispievatelia SaveSDV. Nijako nesúvisí so Stardew Valley ani ConcernedApe. Nie je to oficiálny produkt Stardew Valley.","main_title":"SaveSDV v1.0 - editor uložených hier Stardew Valley","editing_title":"SaveSDV - Úprava uloženej hry ({name})","backups_window":"SaveSDV - Zálohy"},
    "Svenska": {"language":"Språk","edit_save":"Redigera sparfil","view_backups":"Visa säkerhetskopior","github":"GitHub","choose_file":"Öppna sparfil","invalid":"Fel","saved":"Sparfilen ändrades.","backup_created":"En säkerhetskopia av den gamla sparfilen skapades:\n{path}","mods_title":"Moddar upptäcktes","mods_warning":"SaveSDV har upptäckt moddar i din sparfil. Moddar stöds inte fullt ut av SaveSDV och kan förstöra eller korrumpera din sparfil. Skapa alltid säkerhetskopior när du använder SaveSDV.","player_name":"Spelarnamn","farm_name":"Gårdsnamn","money":"Pengar","save_changes":"Spara ändringar","cancel":"Tillbaka","backups_title":"Tillgängliga säkerhetskopior","restore":"Extrahera säkerhetskopia","no_backups":"Det finns inga säkerhetskopior ännu.","restore_done":"Säkerhetskopian extraherades till:\n{path}","backup_confirm":"Före varje ändring skapar SaveSDV automatiskt en säkerhetskopia av hela sparmappen.","footer":"Skapat av FedotovDev och SaveSDV-bidragsgivare. Inte anslutet till Stardew Valley eller ConcernedApe på något sätt. Inte en officiell Stardew Valley-produkt.","main_title":"SaveSDV v1.0 - Stardew Valley sparredigerare","editing_title":"SaveSDV - Redigerar sparfil ({name})","backups_window":"SaveSDV - Säkerhetskopior"},
    "Suomi": {"language":"Kieli","edit_save":"Muokkaa tallennusta","view_backups":"Näytä varmuuskopiot","github":"GitHub","choose_file":"Avaa tallennus","invalid":"Virhe","saved":"Tallennus muokattiin onnistuneesti.","backup_created":"Vanhan tallennuksen varmuuskopio luotiin:\n{path}","mods_title":"Modeja havaittu","mods_warning":"SaveSDV havaitsi modeja tallennustiedostossasi. SaveSDV ei tue modeja täysin, ja ne voivat rikkoa tai vioittaa tallennuksesi. Luo aina varmuuskopio käyttäessäsi SaveSDV:tä.","player_name":"Pelaajan nimi","farm_name":"Maatilan nimi","money":"Raha","save_changes":"Tallenna muutokset","cancel":"Takaisin","backups_title":"Saatavilla olevat varmuuskopiot","restore":"Pura varmuuskopio","no_backups":"Varmuuskopioita ei vielä ole.","restore_done":"Varmuuskopio purettiin kohteeseen:\n{path}","backup_confirm":"Ennen jokaista muokkausta SaveSDV luo automaattisesti varmuuskopion koko tallennuskansiosta.","footer":"Tekijät FedotovDev ja SaveSDV:n avustajat. Ei millään tavalla sidoksissa Stardew Valleyhin tai ConcernedApeen. Ei ole virallinen Stardew Valley -tuote.","main_title":"SaveSDV v1.0 - Stardew Valley -tallennuseditori","editing_title":"SaveSDV - Muokataan tallennusta ({name})","backups_window":"SaveSDV - Varmuuskopiot"},
    "Български": {"language":"Език","edit_save":"Редактиране на запис","view_backups":"Преглед на архиви","github":"GitHub","choose_file":"Отвори запис","invalid":"Грешка","saved":"Записът е редактиран успешно.","backup_created":"Създаден е архив на стария запис:\n{path}","mods_title":"Открити са модове","mods_warning":"SaveSDV откри модове във вашия запис. Модовете не се поддържат напълно от SaveSDV и могат да повредят или разбият записа. Винаги създавайте архиви, когато използвате SaveSDV.","player_name":"Име на играча","farm_name":"Име на фермата","money":"Пари","save_changes":"Запази промените","cancel":"Назад","backups_title":"Налични архиви","restore":"Разархивирай","no_backups":"Все още няма архиви.","restore_done":"Архивът е разпакетиран в:\n{path}","backup_confirm":"Преди всяка промяна SaveSDV автоматично създава архив на цялата папка на записа.","footer":"Създадено от FedotovDev и участниците в SaveSDV. По никакъв начин не е свързано със Stardew Valley и ConcernedApe. Не е официален продукт на Stardew Valley.","main_title":"SaveSDV v1.0 - редактор на Stardew Valley записи","editing_title":"SaveSDV - Редактиране на запис ({name})","backups_window":"SaveSDV - Архиви"},
    "Српски": {"language":"Језик","edit_save":"Уреди сачувану игру","view_backups":"Прикажи резервне копије","github":"GitHub","choose_file":"Отвори сачувану игру","invalid":"Грешка","saved":"Сачувана игра је успешно измењена.","backup_created":"Направљена је резервна копија старе сачуване игре:\n{path}","mods_title":"Откривени су модови","mods_warning":"SaveSDV је открио модове у вашој сачуваној игри. Модови нису у потпуности подржани и могу оштетити или покварити сачувану игру. Увек направите резервне копије када користите SaveSDV.","player_name":"Име играча","farm_name":"Име фарме","money":"Новац","save_changes":"Сачувај промене","cancel":"Назад","backups_title":"Доступне резервне копије","restore":"Распакуј резервну копију","no_backups":"Још нема резервних копија.","restore_done":"Резервна копија је распакована у:\n{path}","backup_confirm":"Пре сваке измене SaveSDV аутоматски прави резервну копију целе фасцикле сачуване игре.","footer":"Направили FedotovDev и сарадници SaveSDV. Није ни на који начин повезано са Stardew Valley и ConcernedApe. Није званични Stardew Valley производ.","main_title":"SaveSDV v1.0 - уређивач Stardew Valley сачуваних игара","editing_title":"SaveSDV - Уређивање ({name})","backups_window":"SaveSDV - Резервне копије"},
    "中文": {"language":"语言","edit_save":"编辑存档","view_backups":"查看备份","github":"GitHub","choose_file":"打开存档","invalid":"错误","saved":"存档修改成功。","backup_created":"已创建旧存档备份：\n{path}","mods_title":"检测到模组","mods_warning":"SaveSDV 检测到你的存档中存在模组。请注意，SaveSDV 不完全支持模组，它们可能导致存档损坏或无法使用。使用 SaveSDV 时请务必创建备份。","player_name":"玩家名称","farm_name":"农场名称","money":"金钱","save_changes":"保存更改","cancel":"返回","backups_title":"可用备份","restore":"解压备份","no_backups":"还没有备份。","restore_done":"备份已解压到：\n{path}","backup_confirm":"每次修改前，SaveSDV 都会自动备份整个存档文件夹。","footer":"由 FedotovDev 和 SaveSDV 贡献者制作。与 Stardew Valley 和 ConcernedApe 没有任何关联。不是官方 Stardew Valley 产品。","main_title":"SaveSDV v1.0 - Stardew Valley 存档编辑器","editing_title":"SaveSDV - 正在编辑存档 ({name})","backups_window":"SaveSDV - 备份"},
    "日本語": {"language":"言語","edit_save":"セーブデータを編集","view_backups":"バックアップを見る","github":"GitHub","choose_file":"セーブを開く","invalid":"エラー","saved":"セーブデータを正常に編集しました。","backup_created":"古いセーブデータのバックアップを作成しました:\n{path}","mods_title":"Modを検出","mods_warning":"SaveSDV はセーブデータ内にModを検出しました。ModはSaveSDVで完全にはサポートされておらず、セーブデータを壊したり破損させたりする可能性があります。SaveSDVを使用するときは必ずバックアップを作成してください。","player_name":"プレイヤー名","farm_name":"農場名","money":"お金","save_changes":"変更を保存","cancel":"戻る","backups_title":"利用可能なバックアップ","restore":"バックアップを展開","no_backups":"まだバックアップはありません。","restore_done":"バックアップを展開しました:\n{path}","backup_confirm":"編集前にSaveSDVはセーブフォルダ全体を自動的にバックアップします。","footer":"FedotovDev と SaveSDV コントリビューターによって作成。Stardew Valley および ConcernedApe とは一切関係ありません。公式 Stardew Valley 製品ではありません。","main_title":"SaveSDV v1.0 - Stardew Valley セーブエディター","editing_title":"SaveSDV - セーブ編集中 ({name})","backups_window":"SaveSDV - バックアップ"},
    "한국어": {"language":"언어","edit_save":"세이브 편집","view_backups":"백업 보기","github":"GitHub","choose_file":"세이브 열기","invalid":"오류","saved":"세이브가 성공적으로 수정되었습니다.","backup_created":"기존 세이브의 백업이 생성되었습니다:\n{path}","mods_title":"모드 감지","mods_warning":"SaveSDV가 세이브 파일에서 모드를 감지했습니다. 모드는 SaveSDV에서 완전히 지원되지 않으며 세이브를 손상시킬 수 있습니다. SaveSDV를 사용할 때는 항상 백업을 만드세요.","player_name":"플레이어 이름","farm_name":"농장 이름","money":"돈","save_changes":"변경 사항 저장","cancel":"뒤로","backups_title":"사용 가능한 백업","restore":"백업 압축 풀기","no_backups":"아직 백업이 없습니다.","restore_done":"백업을 다음 위치에 풀었습니다:\n{path}","backup_confirm":"편집하기 전에 SaveSDV는 전체 세이브 폴더를 자동으로 백업합니다.","footer":"FedotovDev와 SaveSDV 기여자들이 제작했습니다. Stardew Valley 및 ConcernedApe와 어떠한 관련도 없습니다. 공식 Stardew Valley 제품이 아닙니다.","main_title":"SaveSDV v1.0 - Stardew Valley 세이브 편집기","editing_title":"SaveSDV - 세이브 편집 중 ({name})","backups_window":"SaveSDV - 백업"},
    "हिन्दी": {"language":"भाषा","edit_save":"सेव संपादित करें","view_backups":"बैकअप देखें","github":"GitHub","choose_file":"सेव खोलें","invalid":"त्रुटि","saved":"सेव सफलतापूर्वक संपादित हुई।","backup_created":"पुरानी सेव का बैकअप बनाया गया:\n{path}","mods_title":"मॉड पाए गए","mods_warning":"SaveSDV ने आपकी सेव फ़ाइल में मॉड पाए हैं। कृपया ध्यान दें कि मॉड SaveSDV द्वारा पूरी तरह समर्थित नहीं हैं और आपकी सेव को खराब या भ्रष्ट कर सकते हैं। SaveSDV का उपयोग करते समय हमेशा बैकअप बनाएं।","player_name":"खिलाड़ी का नाम","farm_name":"फार्म का नाम","money":"पैसे","save_changes":"बदलाव सहेजें","cancel":"वापस","backups_title":"उपलब्ध बैकअप","restore":"बैकअप निकालें","no_backups":"अभी कोई बैकअप नहीं है।","restore_done":"बैकअप यहां निकाला गया:\n{path}","backup_confirm":"हर बदलाव से पहले SaveSDV पूरे सेव फ़ोल्डर का स्वतः बैकअप बनाता है।","footer":"FedotovDev और SaveSDV योगदानकर्ताओं द्वारा बनाया गया। Stardew Valley और ConcernedApe से किसी भी तरह संबद्ध नहीं। आधिकारिक Stardew Valley उत्पाद नहीं है।","main_title":"SaveSDV v1.0 - Stardew Valley सेव एडिटर","editing_title":"SaveSDV - सेव संपादित हो रही है ({name})","backups_window":"SaveSDV - बैकअप"},
}

LANGUAGES = list(TRANSLATIONS)


def tr(lang: str, key: str, **kwargs) -> str:
    table = TRANSLATIONS.get(lang, TRANSLATIONS["English"])
    value = table.get(key, TRANSLATIONS["English"].get(key, key))
    return value.format(**kwargs)
